### ISSUE TITLE
My token is showing unverified on the web

### ISSUE THREAD

**Issue by arunwebber** [MuesliSwapTeam/muesliswap-token-verification#141]
I have given merge request and its got merged already but after the update on the website it is showing that the token is unverified. https://github.com/MuesliSwapTeam/muesliswap-token-verification/pull/131

https://muesliswap.com/swap/expert?base=.&quote=2d420236ffaada336c21e3f4520b799f6e246d8618f2fc89a4907da6.4564756c6164646572546f6b656e  may i know what is going on?

**Comment by MuesliSwapTeam** [comment]
Sorry for the inconvenience; the problem has been fixed now.
