### ISSUE TITLE
KING TOKEN 

### ISSUE THREAD

**Issue by Asafy77** [MuesliSwapTeam/muesliswap-token-verification#170]
PLEASE VERIFY :
$KING TOKEN
TICKER : KING

Policy ID | 2edc63d29e94747f7ef65df559260c994d2ecfe208ac6afa56451738
Fingerprint : asset1gz5ssnup9m97ju3z9d522wc3m78krvyed7f8ak
social 👍
https://twitter.com/KING__cardano
https://www.king4cardano.com/
discord : https://discord.com/channels/1060165262508310580/1060165265490456648

**Comment by MuesliSwapTeam** [comment]
Hi, thanks a lot for your request!
Could you please create a pull request and submit the verification fee to get verified?

**Comment by Asafy77** [comment]
Hi, thanks !
dont know how to open a pull request - send an explanation how to do it(if
you must)
   the Transaction Id  for verification fee:
76e04b35e04c76743bacea490ff8d1d31fbc3c8ec0e1207afe0fbefcae714744

‫בתאריך יום ו׳, 10 בפבר׳ 2023 ב-16:18 מאת ‪MuesliSwap Team‬‏ <‪
***@***.***‬‏>:‬

**Comment by MuesliSwapTeam** [comment]
No worries, your token has just been verified and will soon show up as verified on Muesliswap.

**Comment by Asafy77** [comment]
Thanks a lot.

👍🏼👍🏼👍🏼👍🏼🥳🥳🥳🥳🥳בתאריך יום ב׳, 13 בפבר׳ 2023 ב-0:19 מאת
MuesliSwap Team ***@***.***>:

**Comment by Asafy77** [comment]
Thank you 🙏🏽 🥳🥳🥳🥳🥳🎉🎉🎉
בתאריך יום ב׳, 13 בפבר׳ 2023 ב-0:19 מאת MuesliSwap Team <
***@***.***>:
